Repository WatWowMap/MapJS, pull requests merged in 2020-09, with the labels that each got.

#133 Add SQL index hints for getPokemon
  src/data/map.js
Labels: needs-testing

#151 Add gzip compression middleware
  src/index.js
Labels: enhancement

#158 Add support for mysql 5.7 again
  src/data/map.js
Labels: needs-testing

#41 Custom User Settings
  src/rarity.json
  src/routes/api.js
  src/views/index-css.mustache
  src/views/index-js.mustache
  src/views/index.mustache
  static/locales/_en.json
Labels: enhancement

#144 Add scan areas permission
  src/config.example.json
  src/index.js
  src/services/discord.js
  src/views/index.mustache
Labels: enhancement

#150 Rate Limiting
  package-lock.json
  package.json
  src/config.example.json
  src/index.js
  src/routes/ui.js
  src/views/429.mustache
  src/views/index-js.mustache
Labels: enhancement

#90 Update Existing Weather Cells Upon Change
  src/views/index-js.mustache
Labels: needs-testing

#143 MySQL sessions + Prevent multiple sessions
  package-lock.json
  package.json
  src/config.example.json
  src/index.js
  src/services/session-store.js
Labels: enhancement, needs-testing

#220 Make raid pokemon same size as quest
  static/js/index.js
Labels: enhancement

#238 Hide areas dropdown when empty
  src/routes/ui.js
  src/views/navbar.mustache
Labels: bug

#235 Fix nest and quest search icon paths
  src/data/map.js
  src/index.js
  static/js/index.js
Labels: bug

#216 Selective Pokemon Timers + Filter pokemon by verified despawn timer
  package-lock.json
  src/configs/default.json
  src/data/default.js
  src/data/map.js
  src/routes/api.js
  src/views/index.mustache
  static/css/index.css
  static/img/misc/verified.png
  static/js/index.js
  static/locales/_en.json
Labels: enhancement

#230 Ingress Portals
  src/configs/config.example.json
  src/configs/default.json
  src/data/default.js
  src/data/map.js
  src/index.js
  src/routes/api.js
  src/services/discord.js
  src/views/index.mustache
  static/css/index.css
  static/img/misc/portal.png
  static/js/index.js
  static/locales/_en.json
Labels: enhancement

#236 Mega Evolution Quest Filters
  src/data/map.js
  src/routes/api.js
  static/js/index.js
  static/locales/_en.json
Labels: enhancement
