Repository WatWowMap/MapJS, pull requests merged in 2020-11, with the labels that each got.

#274 Fix Sizing
  package-lock.json
  src/configs/default.json
  src/data/default.js
  src/routes/api.js
  src/views/index.mustache
  static/js/index.js
Labels: enhancement

#276 Scale down raids to avoid confusion
  src/configs/default.json
Labels: enhancement

#286 Support Gen 6 Pokemon
  src/data/map.js
  src/routes/api.js
  static/data/masterfile.json
  static/js/index.js
Labels: enhancement

#288 docs: Update docker compose + documentation
  docker-compose.example.yml
  docs/install/docker.md
Labels: enhancement

#113 Fix tooltip location
  src/views/header.mustache
  static/js/index.js
Labels: needs-testing

#285 Support for Mega/L40/L41/L50/L51 PVP Stats (Chuck)
  package-lock.json
  src/configs/default.json
  src/data/default.js
  src/data/map.js
  src/routes/api.js
  src/views/index.mustache
  static/js/index.js
  static/locales/_en.json
Labels: enhancement, needs-testing
